import "./globals.css";
 import { Montserrat } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
export const metadata = {
  title: "Hacienda",
  description: "Generated by create next app",
};
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"],  
});
config.autoAddCss = false;
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
